### ISSUE TITLE
badge is not working in HTC

### ISSUE THREAD

**Issue by gurwin** [wcoder/ShortcutBadger#12]
actually, I tried this solution and it is properly running in the phone but it's not showing the numeric value on the app icon.

**Comment by yauhenipakala** [comment]
Hi @gurwin 

Could you provide me some details:

- Device version
- Which launcher used
- Android version

**Comment by gurwin** [comment]
hi @wcoder 
 I am using
Android Version: 6.0
Device: HTC desire 816 dual sim

**Comment by yauhenipakala** [comment]
I haven't the ability to reproduce this issue.

Maybe this will help your (add these to your AndroidManifest.xml):
```xml
<uses-permission android:name="com.sec.android.provider.badge.permission.READ" tools:node="remove"/>
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" tools:node="remove"/>
<uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS" tools:node="remove"/>
<uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT" tools:node="remove"/>
```

If it doesn't help, create an issue on original repository: https://github.com/leolin310148/ShortcutBadger

**Comment by gurwin** [comment]
hi @wcoder 
I already added these line into my manifest. but I have one more question. I am new with Xamarin and I have no idea whats going on. Can you please tell me where should I have to add these line. In which class please mention the name of the class.

Add the codes below:

int badgeCount = 1;
ShortcutBadger.ApplyCount(context, badgeCount);

**Comment by yauhenipakala** [comment]
Everywhere you have context, for example on your Activity:

```csharp
public class MainActivity : AppCompatActivity
{
	protected override void OnCreate(Bundle savedInstanceState)
	{
		base.OnCreate(savedInstanceState);

		SetContentView(Resource.Layout.activity_main);

		//...

		ShortcutBadger.ApplyCount(this, 6);
	}

	//...
}
```

**Comment by gurwin** [comment]
![again](https://user-images.githubusercontent.com/40004944/41551796-f9135cc6-72fa-11e8-83b4-6f007c6c4478.PNG)
hi @wcoder 
Thank you for your help. I changed my code according to your steps. But now when I am trying to run my code it is showing one error. Can you please tell me whats wrong with this code and where I am doing wrong. Its showing a green dot on application icon instead of numeric value.
![capture](https://user-images.githubusercontent.com/40004944/41551538-24669bb4-72fa-11e8-8521-c87684a89bd6.PNG)

**Comment by yauhenipakala** [comment]
Hi @gurwin
Sorry for my late reply.
I think it can be a problem on emulator, what happens on device?

**Comment by gurwin** [comment]
On emulator it shows a single green dot. But incase of phone its nit
showing anything.

**Comment by yauhenipakala** [comment]
I added binding of native android library here: https://github.com/wcoder/ShortcutBadger/tree/feature/binding-library/src/Xam.ShortcutBadger.Binding

You can download and use sources of this repository.

If that doesn't solve this issue, please report to the original repo for a quick fix (https://github.com/leolin310148/ShortcutBadger/issues)
