### ISSUE TITLE
Sync with original version (1.1.23)

### ISSUE THREAD

**Issue by yauhenipakala** [wcoder/ShortcutBadger#15]

**Comment by raver99** [comment]
Hi @wcoder,

I find this plugin very helpful for us Xamarin Developers. Thank you for that.
As it has not been synced with the original for some time, do you think it would be possible to update it in the near future?

Just a heads up: there is a new version 1.1.23, but it seems that it is not on maven central yet.

Thanks.

**Comment by yauhenipakala** [comment]
Hi @raver999 !
Sure, I'll update library asap.

**Comment by yauhenipakala** [comment]
Unfortunately, as I can see the latest version in maven is 1.1.22

Related issue: https://github.com/leolin310148/ShortcutBadger/issues/336
