### ISSUE TITLE
xiaomi2 didn't work ,the minu version miui7.5 Can you please provide a solution asap

### ISSUE THREAD

**Issue by guoleigl** [wcoder/ShortcutBadger#4]

**Comment by yauhenipakala** [comment]
Hi @guoleigl, thanks for your feedback!

Please check this wiki: https://github.com/leolin310148/ShortcutBadger/wiki/Xiaomi-Device-Support
And try this solution: https://github.com/wcoder/ShortcutBadger/blob/master/example/ExampleShortcutBadgerApp/ExampleShortcutBadgerApp/MainActivity.cs#L38
