### ISSUE TITLE
i was tring to use the binding for  shortcutbadger by android,but it not worked.

### ISSUE THREAD

**Issue by ZZhangXiao** [wcoder/ShortcutBadger#7]
if the reason you get,please tell me ,thx.

**Comment by yauhenipakala** [comment]
Hi @ZZhangXiao, thanks for your feedback!

What device (firmware) or emulator do you use?
Which Android version?

**Comment by ZZhangXiao** [comment]
thx for your reply.
MIUI9, Android 7.0
I find the problem where.
MIUI   check the notifyId,If two notifyId are the same, it see as one and not add the badge.

**Comment by ZZhangXiao** [comment]
I pointed to the wrong button with closed.
Maybe it's a bug  by shortcutbadger.
If i want add above 1 badge  will must make more than 1 notify in the bar. not consistent with expectations

**Comment by yauhenipakala** [comment]
@ZZhangXiao, currently I synchronized code from original repository, and release new version [1.1.19](https://www.nuget.org/packages/Xamarin.ShortcutBadger/1.1.19)

Please read original wiki about support Xiaomi devices: https://github.com/leolin310148/ShortcutBadger/wiki/Xiaomi-Device-Support

And check this solution: https://github.com/wcoder/ShortcutBadger/blob/master/example/ExampleShortcutBadgerApp/ExampleShortcutBadgerApp/MainActivity.cs#L38

It works for me on MIUI 9.0

**Comment by ZZhangXiao** [comment]
Thx~ . I tried to do it yesterday，It works now.
